param(
    [Parameter(Mandatory = $true)]
    [string] $InstallRoot,
    [string] $AdminPassword
)

$ErrorActionPreference = 'Stop'
$resolvedRoot = [IO.Path]::GetFullPath($InstallRoot).TrimEnd('\')
$serverRoot = Join-Path $resolvedRoot 'server'
$dataRoot = Join-Path $resolvedRoot 'data'
$sourcePath = Join-Path $serverRoot 'StartServer64.bat'
$destinationPath = Join-Path $resolvedRoot 'manager\generated-start-server.bat'

if (-not (Test-Path -LiteralPath $sourcePath)) {
    throw "The official 64-bit launcher was not found: $sourcePath"
}

$content = Get-Content -LiteralPath $sourcePath -Raw
$content = $content -replace '(?im)^\s*@?cd\s+/d\s+"%~dp0"\s*$', ('@cd /d "{0}"' -f $serverRoot)
$content = $content -replace '(?im)^\s*pause\s*$', ''
$content = $content -replace '(?i)-Xms\d+[mg]', '-Xms2g'
$content = $content -replace '(?i)-Xmx\d+[mg]', '-Xmx8g'

$lines = $content -split '\r?\n'
$found = $false
$arguments = @(
    '-servername "zedwatch"'
    ('-cachedir="{0}"' -f $dataRoot)
)
if (-not [string]::IsNullOrWhiteSpace($AdminPassword)) {
    $escapedPassword = $AdminPassword.Replace('"', '""')
    $arguments += ('-adminpassword "{0}"' -f $escapedPassword)
}
$suffix = ' ' + ($arguments -join ' ')

for ($index = 0; $index -lt $lines.Count; $index++) {
    if ($lines[$index] -match 'zombie\.network\.GameServer' -and $lines[$index] -notmatch '(?i)-servername') {
        $lines[$index] = $lines[$index].TrimEnd() + $suffix
        $found = $true
    }
}

if (-not $found -and $content -notmatch '(?i)-servername') {
    throw 'The installed StartServer64.bat layout was not recognized. ZedWatch did not modify the vendor launcher.'
}

$header = @(
    '@echo off'
    'rem Generated by ZedWatch from the installed Project Zomboid launcher.'
    'rem This file is regenerated after server updates. Edit settings in ZedWatch instead.'
)
$output = ($header + $lines) -join "`r`n"
Set-Content -LiteralPath $destinationPath -Value $output -Encoding ASCII
Write-Output $destinationPath
